### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by ju5t** [supportpal/api-client-php#134]
First of all, thanks for open sourcing this client. While very useful, I have some questions too.

In your documentation, it mentions the following code sample to send a message:

```php
$message = $api->getTicketApi()->postMessage(['ticket_id' => 1, 'user_id' => 1, 'text' => 'Message']);
```

That doesn't work. This should probably be `getApiClient()->postMessage($messageArray)` as `postMessage` only accepts a `CreateMessage` class. It's not really a problem, but since this class doesn't come with a constructor, you have to use setters to set its properties, which to me, feels like a step back these days, especially as 7.4 is there for a while now.

When would you expect to bump the client to PHP >7.4? This way, all properties can be type hinted and public.

I'm lost when it comes to attachments. I have an instance of `CreateMessage`. This comes with a `setAttachment` property but it only accepts an array or null. Where can I find how to add one or more attachments to the message I'm sending?

**Comment by Gaitholabi** [comment]
Thank you for using the client. It looks like the documentation is using a slightly older version of the client, we will update it shortly.  The current simpler way to do this now is by using the fill method. 
```
$createMessage = (new CreateMessage)->fill(['ticket_id' => 1, 'user_id' => 1, 'text' => 'Message']);
$message = $api->getTicketApi()->postMessage(createMessage);
```
As for the `setAttachment`,  following https://api.supportpal.com/api.html#ticket-message-post, this would currently expect an array of the key-valued array as follows:
```
$attachments = [
    ['filename' => 'test', 'contents' => 'base-64-string',],
     ['filename' => 'test2', 'contents' => 'base-64-string-2',]
 ];
$createMessage->setAttachment($attachments);
```
We're not sure when we'd be able to bump this to PHP-7.4 due to having other internal dependencies, but we'd love to do that asap.

Sorry for the confusion, hope that this makes it clearer!

**Comment by ju5t** [comment]
I got things working, but the attachment implementation feels off. I posted parts of the below in the PR too, but that got closed around the same time so you have probably missed it.

Out of curiosity, why are you using arrays to create an attachment? There is an Attachment model. Why don't you modify this model so it accepts the base64 encoded content? Or have two properties, one of encoded, the other for unencoded?

Just to show our own abstracted implementation of your client, we're now doing this:

```php
$message = (new Message(content: ''))
    ->addAttachment(new Attachment(
        filename: 'filename.txt',
        base64content: base64_encode('content'),
    ));
```

This is PHP8 by the way, so we got named properties ❤️

It feels more intuitive for me/us. We've abstracted the message because we don't want to closely couple your implementation with ours. We're not planning to use another system, but this gives us flexibility.

Also, your client is very literal. I get that. It's easier and the client code matches 1 to 1 with the API. It isn't very fluid though. Our abstraction allows us to take this message and reply to a ticket like so:

```php
$ticket->as($operator)->postReply($message);
```

In the background this will still use `CreateMessage` and add attachments, of course 😄 

I am very happy that you've made this client though. We would have to abstract things away either way. But it would be great if future changes would be easier to grasp, without having to know if we have to use `getTicketApi` with what method.

**Comment by Gaitholabi** [comment]
The Attachment object we currently have maps another endpoint. The way I try to think about our models is that every attribute would map to an attribute in the API.  

The idea was to minimize instantiations as we could since previous implementations were using arrays, thus, the transition would mostly be easier this way, but yes I agree that including an Attachment object, and having constructors would make things easier. This is definitely something to look at for the next iterations of this work to see how we can improve. 

Your feedback is very highly appreciated, and will surely be put into consideration.
